# Generated by Django 2.1.7 on 2019-02-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Barang',
        ),
    ]
